version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-CTP2.1-ubuntu-22.04
    container_name: starcatcher-sqlserver
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - starcatcher-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


volumes:
  sqlserver_data:
    driver: local

networks:
  starcatcher-network:
    driver: bridge