### Configurar variável de ambiente
@host = http://localhost:5297

### Fazer login para obter o token
POST {{host}}/api/Usuario/login
Content-Type: application/json

{
  "email": "carlos.pereira@exemplo.com",
  "senha": "senhaSegura789"
}

### Extrair o token da resposta do login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIzIiwiZW1haWwiOiJjYXJsb3MucGVyZWlyYUBleGVtcGxvLmNvbSIsIm5hbWUiOiJDYXJsb3MgUGVyZWlyYSIsIm5iZiI6MTc1NTc5NTQxOSwiZXhwIjoxNzg3MzUzMDE5LCJpc3MiOiJzZXVpc3N1ZXIiLCJhdWQiOiJzZXVhdWRpZW5jZSJ9.1I17zLXOsGOw2iP25eEyY4F0Kd1ESkOiBMSCNtiXZVk
### ==================================================
### OPERAÇÕES DE CONSÓRCIO
### ==================================================

### 1. Criar novo consórcio (com cotas automáticas)
POST {{host}}/api/consorcio
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Consórcio Imóvel Premium",
  "codigo": "IMP2024",
  "valorBem": 250000.00,
  "quantidadeCotas": 2,
  "prazoMeses": 60,
  "taxaAdministracao": 15.00,
  "fundoReserva": 2500.00,
  "dataInicio": "2025-01-01T00:00:00"
}

### 2. Listar todos os consórcios ativos
GET {{host}}/api/consorcio/active
Accept: application/json
Authorization: Bearer {{token}}


### 3. Listar todos os consórcios (ativos e inativos)
GET {{host}}/api/consorcio/
Accept: application/json
Authorization: Bearer {{token}}


### 4. Buscar consórcio por ID
GET {{host}}/api/consorcio/17
Accept: application/json
Authorization: Bearer {{token}}


### 5. Buscar consórcio com suas cotas
GET {{host}}/api/consorcio/17/with-cotas
Accept: application/json
Authorization: Bearer {{token}}


### 6. Buscar cotas disponíveis de um consórcio
GET {{host}}/api/consorcio/17/available-cotas
Accept: application/json
Authorization: Bearer {{token}}


### 7. Atribuir cota ao usuário
POST {{host}}/api/consorcio/assign-cota
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cotaId": 23,
  "usuarioId": 1
}


### 8. Atualizar consórcio
PUT {{host}}/api/consorcio/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "nome": "Consórcio Imóvel Premium Plus",
  "codigo": "IMP2024",
  "valorBem": 280000.00,
  "prazoMeses": 120,
  "taxaAdministracao": 16.00,
  "fundoReserva": 3000.00,
  "dataInicio": "2024-01-01T00:00:00",
  "ativo": true
}


### 9. Deletar consórcio (vai deletar as cotas também)
DELETE {{host}}/api/consorcio/20
Accept: application/json
Authorization: Bearer {{token}}


### 10. Adicionar cotas a um consórcio existente
POST {{host}}/api/consorcio/17/cotas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantidade": 1
}
